import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalClickSound from "@/components/GlobalClickSound";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="fixed top-0 left-0 w-full h-screen">
          
          <video
            src={"/backgroundVideo2.mp4"}
            className="w-full h-full object-cover -z-[1]"
            loop
            autoPlay
            playsInline
            muted
            preload="auto" 
          />
        </div>
        

        <main className="relative z-10 text-white scroll-smooth">
          {/* <GlobalClickSound/> */}
          {children}</main>
      </body>
    </html>
  );
}
